---
title: "Gráficos do Dadostransparentes"
author: "Zé"
date: "13/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = TRUE)
```


```{r, echo=FALSE, multi.col = T}
suppressWarnings(source('dadostransparentes.R', encoding = 'UTF-8'))

acumulados <- get_series()
theme_set(theme_minimal())

acumulados %>% 
  ggplot(., aes(x = Date)) +
  geom_line(aes(y = Casos, colour = 'Casos'), size = 1) +
  geom_line(aes(y = Óbitos, colour = 'Óbitos'), size = 1) +
  scale_y_continuous(labels = scales::number) +
  labs(x = 'Data',
       y = 'Número',
       title = 'Casos e óbitos acumulados',
       color = '',
       caption = 'Fonte: www.dadostransparentes.com.br')
  ggplotly()
  
  novos <- get_series(1)
novos %>% 
  ggplot(., aes(x = Date)) +
  geom_line(aes(y = Casos, colour = 'Casos'), size = 1) +
  geom_line(aes(y = Óbitos, colour = 'Óbitos'), size = 1) +
  scale_y_continuous(labels = scales::comma) +
  labs(x = 'Data',
       y = 'Número',
       title = 'Casos e óbitos novos',
       color = '',
       caption = 'Fonte: www.dadostransparentes.com.br')
  ggplotly()

```

```{r, echo=FALSE}

acumulados %>% 
  tidyr::gather(key = 'Série', value = 'Número', -Date) %>% 
  ggplot(., aes(x = Date)) +
  geom_line(aes(y = Número, colour = Série), size = 1, show.legend = FALSE) +
  facet_wrap(vars(Série), scales = 'free_y') +
  scale_y_continuous(labels = scales::number) +
  scale_x_date(date_breaks = "4 weeks", date_labels = "%b %w") +
  labs(x = 'Data',
       y = 'Número',
       title = 'Casos e óbitos acumulados',
       subtitle = 'As séries foram postas lado a lado',
       caption = 'Fonte: www.dadostransparentes.com.br')
  ggplotly()
  
  novos %>% 
  tidyr::gather(key = 'Série', value = 'Número', -Date) %>% 
  ggplot(., aes(x = Date)) +
  geom_line(aes(y = Número, colour = Série), size = 1, show.legend = FALSE) +
  facet_wrap(vars(Série), scales = 'free_y') +
  scale_y_continuous(labels = scales::number) +
  scale_x_date(date_breaks = "4 weeks", date_labels = "%b %w") +
  labs(x = 'Data',
       y = 'Número',
       title = 'Casos e óbitos novos',
       subtitle = 'As séries foram postas lado a lado',
       caption = 'Fonte: www.dadostransparentes.com.br'
  ) 
  ggplotly()

```
